### ISSUE TITLE
为什么直接编译的无法自动启动nginx和开发者工具呢？

### ISSUE THREAD

**Issue by veeking** [seancheung/wxdevtool#1]
从docker上pull最早的版本docker run时候是可以自动启动开发者工具和portwatcher的，但是拿源码docker编译出来不会自动启动？

**Comment by seancheung** [comment]
因为微信开发工具默认是没有开启监听的。镜像里entrypoint会判断微信开发工具是否有完成初始化配置，没有的话是不会启动服务的~
之所以这么处理是因为微信开发工具从某个版本之后没法通过魔改配置文件来设置默认开启监听；所以需要先通过GUI手动开启。
具体可以参考readme里的rc tag部分的描述

**Comment by veeking** [comment]
现在新版本开发工具已经将node-sync-ipc-nwjs模块移除了，所以按现在您的直接build的话会失败，我把您的fork过来改了，感兴趣可以看看我的repo.

**Comment by veeking** [comment]
> 因为微信开发工具默认是没有开启监听的。镜像里entrypoint会判断微信开发工具是否有完成初始化配置，没有的话是不会启动服务的~
> 之所以这么处理是因为微信开发工具从某个版本之后没法通过魔改配置文件来设置默认开启监听；所以需要先通过GUI手动开启。
> 具体可以参考readme里的rc tag部分的描述
---------------------------------------------------------------------
现在新版本开发工具已经将node-sync-ipc-nwjs模块移除了，所以按现在您的直接build的话会失败，我把您的fork过来改了，感兴趣可以看看我的repo. 另外有个问题我一直很疑惑就是：您dockerfile里哪行是如何自动启动开发者工具的，我看也没有调用CMD来执行呀？

**Comment by seancheung** [comment]
> > 因为微信开发工具默认是没有开启监听的。镜像里entrypoint会判断微信开发工具是否有完成初始化配置，没有的话是不会启动服务的~
> > 之所以这么处理是因为微信开发工具从某个版本之后没法通过魔改配置文件来设置默认开启监听；所以需要先通过GUI手动开启。
> > 具体可以参考readme里的rc tag部分的描述
> 
> 现在新版本开发工具已经将node-sync-ipc-nwjs模块移除了，所以按现在您的直接build的话会失败，我把您的fork过来改了，感兴趣可以看看我的repo. 另外有个问题我一直很疑惑就是：您dockerfile里哪行是如何自动启动开发者工具的，我看也没有调用CMD来执行呀？

是的因为微信开发工具更新老会造成breaking所以旧的build方式没法支持新的版本。

Dockerfile的entrypoint在被引用的VNC镜像(dorowu/ubuntu-desktop-lxde-vnc:bionic)里声明的, 其实就是启动了supervisord(进程管理工具)服务。`wxdevtool.conf`里的两个program，一个是`wxdevtool`启动微信开发者工具，一个是`portwatcher`用来监听其端口进行反向代理。
你可以使用`docker image inspect -f '{{printf "entrypoint: %s\ncmd: %s" .Config.Entrypoint .Config.Cmd}}' <镜像名称或ID>`来检视镜像的`entrypoint`和默认`cmd`

这个工具本来是想做远程自动化构建的，后来发现性能实在不行，并且无法完全headless(比如登陆)，就没怎么维护了。
